name: Deploy

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '24.x'
  OUTPUT_DIR: 'build'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        run: |
          # Deploy all static assets with long cache
          aws s3 sync ./${{ env.OUTPUT_DIR }}/ s3://docs.chrom.ar/ \
            --delete \
            --cache-control "public, max-age=31536000, immutable" \
            --exclude "*.html" \
            --exclude "sitemap.xml" \
            --exclude "404.html" \
            --exclude "assets/js/*.js.map"

          # Deploy HTML files and sitemap with no cache for fresh content
          aws s3 sync ./${{ env.OUTPUT_DIR }}/ s3://docs.chrom.ar/ \
            --delete \
            --cache-control "public, max-age=0, must-revalidate" \
            --exclude "*" \
            --include "*.html" \
            --include "sitemap.xml"

      - name: Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"